name: Build & Test Ticketing MGT Tickets
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Setup .Net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.100
        include-prerelease: true
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Restore
      run: dotnet restore
      working-directory: src/TicketMGT.Core.Api
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/TicketMGT.Core.Api

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: tests/TicketMGT.Core.Api.Tests
